sudo: true

language: python

dist: xenial

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install poetry
  - poetry install

script:
  - export PYTHONPATH=`pwd`; pytest tests/
  - black --check --verbose .
  - flake8 cy_weather_api
