from enum import Enum


class CySkyCon(Enum):
    CLEAR_DAY = "CLEAR_DAY"
    CLEAR_NIGHT = "CLEAR_NIGHT"
    PARTLY_CLOUDY_DAY = "PARTLY_CLOUDY_DAY"
    PARTLY_CLOUDY_NIGHT = "PARTLY_CLOUDY_NIGHT"
    CLOUDY = "CLOUDY"
    LIGHT_HAZE = "LIGHT_HAZE"
    MODERATE_HAZE = "MODERATE_HAZE"
    HEAVY_HAZE = "HEAVY_HAZE"
    LIGHT_RAIN = "LIGHT_RAIN"
    MODERATE_RAIN = "MODERATE_RAIN"
    HEAVY_RAIN = "HEAVY_RAIN"
    STORM_RAIN = "STORM_RAIN"
    FOG = "FOG"
    LIGHT_SNOW = "LIGHT_SNOW"
    MODERATE_SNOW = "MODERATE_SNOW"
    HEAVY_SNOW = "HEAVY_SNOW"
    STORM_SNOW = "STORM_SNOW"
    DUST = "DUST"
    SAND = "SAND"
    WIND = "WIND"
